version: '3.0'
services:
    nginx: 
        image: nginx:1.17
        ports:
            - "80:80"
            - "8080:8080"
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./.htpasswd:/etc/nginx/.htpasswd
            - ./frontend:/usr/src/frontend
            - ./images:/usr/src/images
        depends_on: 
            - backend
    backend:
        build: ./backend/.
        volumes: 
            - ./images:/usr/src/images
        depends_on: 
            - postgres
    postgres:
        image: postgres:12
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment: 
            POSTGRES_USER: vss_user
            POSTGRES_PASSWORD: '123456789'
            POSTGRES_DB: happyface